spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodbox_db
    username: root
    password: "#F00db0xb@ckend#"
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    

server:
  address: localhost
